services:
  nucleo-db:
    image: postgres:17
    environment:
      POSTGRES_DB: nucleo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"

  nucleo-app:
    build: .
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://nucleo-db:5432/nucleo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - nucleo-db
